server:
  port: 8081

spring:
  application:
    name: User Service
  datasource:
    url: jdbc:h2:mem:t2Examen
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 744171173544-ng0m3inasrclkauj7sl6q1cudvh26l6k.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


